src/Entity/SupportRequest.php
<?php

namespace App\Entity;

use App\DTO\SupportRequestDTO;
use DateTime;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SupportRequestRepository")
 */
class SupportRequest
{
    public const DRAFT_STATUS_INDEX    = 0;
    public const SOLVED_STATUS_INDEX   = 1;
    public const REJECTED_STATUS_INDEX = 2;

    public const STATUS_TITLE_LIST = [
        self::DRAFT_STATUS_INDEX    => 'Ожидание решения',
        self::SOLVED_STATUS_INDEX   => 'Решено',
        self::REJECTED_STATUS_INDEX => 'Отклонено',
    ];

    public const ANSWER_STATUS_TITLE_LIST = [
        self::SOLVED_STATUS_INDEX   => 'Решено',
        self::REJECTED_STATUS_INDEX => 'Отклонено',
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(name="id", type="integer")
     */
    private ?int $id;
    /**
     * @ORM\Column(name="title", type="string", length=255)
     */
    private string $title;
    /**
     * @ORM\Column(name="message", type="text", length=10000)
     */
    private string $message;
    /**
     * @ORM\Column(name="status", type="smallint", options={"default" : 0})
     */
    private int $status = 0;
    /**
     * @ORM\Column(name="create_at", type="datetime", nullable=false)
     */
    private DateTime $createAt;
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(name="created_by", referencedColumnName="id", nullable=false)
     */
    private User $createdBy;
    /**
     * @ORM\OneToOne(targetEntity="App\Entity\SupportRequestAnswer", mappedBy="supportRequest")
     */
    private ?SupportRequestAnswer $answer;

    public function __construct(User $user, string $title, string $message)
    {
        $this->createdBy = $user;
        $this->title = $title;
        $this->message = $message;
        $this->createAt = new DateTime();
    }

    public static function createFromDTO(SupportRequestDTO $dto): self
    {
        return new self($dto->getCreatedBy(), $dto->getTitle(), $dto->getMessage());
    }

    public function updateFromDTO(SupportRequestDTO $dto): void
    {
        $this->setTitle($dto->getTitle());
        $this->setMessage($dto->getMessage());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): string
    {
        return $this->title;
    }

    public function setTitle(string $title): void
    {
        $this->title = $title;
    }

    public function getMessage(): string
    {
        return $this->message;
    }

    public function setMessage(string $message): void
    {
        $this->message = $message;
    }

    public function getStatus(): int
    {
        return $this->status;
    }

    public function setStatus(int $status): void
    {
        $this->status = $status;
    }

    public function getStatusTitle(): string
    {
        return self::STATUS_TITLE_LIST[$this->getStatus()];
    }

    public function getCreateAt(): DateTime
    {
        return $this->createAt;
    }

    public function getCreatedBy(): User
    {
        return $this->createdBy;
    }

    public function setCreatedBy(User $createdBy): void
    {
        $this->createdBy = $createdBy;
    }

    public function isAnswered(): bool
    {
        return in_array($this->getStatus(), [self::SOLVED_STATUS_INDEX, self::REJECTED_STATUS_INDEX]);
    }

    public function getAnswer(): ?SupportRequestAnswer
    {
        return $this->answer;
    }

    public function setAnswer(?SupportRequestAnswer $answer): void
    {
        $this->answer = $answer;
    }

    public function getData(): array
    {
        return [
            'id'         => $this->getId(),
            'title'      => $this->getTitle(),
            'message'    => $this->getMessage(),
            'status'     => [
                'id'    => $this->getStatus(),
                'title' => $this->getStatusTitle(),
            ],
            'created_at' => $this->getCreateAt()->format(DATE_ATOM),
            'created_by' => $this->getCreatedBy()->getData(),
        ];
    }
}

src/Form/Type/SupportRequestType.php
<?php

namespace App\Form\Type;

use App\DTO\SupportRequestDTO;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SupportRequestType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, [
                'label' => 'Тема запроса'
            ])
            ->add('message', TextareaType::class, [
                'label' => 'Сообщение запроса'
            ])
            ->add('save', SubmitType::class, ['label' => 'Добавить']);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class'      => SupportRequestDTO::class,
        ]);
    }
}

src/Controller/Api/SupportRequestController.php
<?php

namespace App\Controller\Api;

use App\DTO\SupportRequestAnswerDTO;
use App\DTO\SupportRequestDTO;
use App\Entity\SupportRequest as RequestEntity;
use App\Entity\SupportRequestAnswer;
use App\Entity\User;
use App\FilterOptionCollection\GetSupportRequestListFilterOptionCollection;
use App\Form\Type\SupportRequestAnswerType;
use App\Form\Type\SupportRequestType;
use App\Repository\SupportRequestRepository;
use App\Repository\UserRepository;
use App\Service\SupportRequestApiDataManager;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use function is_null;
use function json_decode;
use function sprintf;

/**
 * @Route("/request")
 */
class SupportRequestController extends AbstractController
{
    private EntityManagerInterface $entityManager;
    private UserRepository $userRepository;

    public function __construct(EntityManagerInterface $entityManager, UserRepository $userRepository)
    {
        $this->entityManager = $entityManager;
        $this->userRepository = $userRepository;
    }

    /**
     * @Route("/list", name="api.request.list")
     */
    public function getSupportRequestListAction(
        Request $request,
        SupportRequestApiDataManager $supportRequestApiDataManager
    ): Response {
        $optionCollection = GetSupportRequestListFilterOptionCollection::buildFromRequest($request);

        return $this->json([
            'success' => true,
            'data'    => $supportRequestApiDataManager->getSupportRequestDataListByFilterOptionCollection($optionCollection),
        ]);
    }

    /**
     * @Route("/show/{id}", name="api.request.show")
     */
    public function getSupportRequestDataAction(
        Request $request,
        int $id,
        SupportRequestRepository $supportRequestRepository
    ): Response {
        $supportRequest = $supportRequestRepository->findById($id);

        if (is_null($supportRequest)) {
            return $this->json([
                'error'   => true,
                'message' => sprintf('Не найдена заявка с id %s.', $id),
            ]);
        }

        return $this->json([
            'success' => true,
            'data'    => $supportRequest->getData(),
        ]);
    }

    /**
     * @Route("/delete/{id}", name="api.request.delete")
     */
    public function deleteSupportRequestDataAction(
        Request $request,
        int $id,
        SupportRequestRepository $supportRequestRepository
    ): Response {
        $user = $this->getUserByBearerToken($request);

        if (is_null($user)) {
            return $this->json([
                'error'   => true,
                'message' => 'Пользователь не авторизован',
            ]);
        }

        $supportRequest = $supportRequestRepository->findById($id);

        if (is_null($supportRequest)) {
            return $this->json([
                'error'   => true,
                'message' => sprintf('Не найдена заявка с id %s.', $id),
            ]);
        }

        if ($supportRequest->getCreatedBy()->getId() !== $user->getId()) {
            return $this->json([
                'error'   => true,
                'message' => 'Удалить заявку может только создатель',
            ]);
        }

        $this->entityManager->remove($supportRequest);
        $this->entityManager->flush();

        return $this->json([
            'success' => true,
        ]);
    }
    /**
     * @Route("/edit/{id}", name="api.request.edit")
     */
    public function editSupportRequestDataAction(
        Request $request,
        int $id,
        SupportRequestRepository $supportRequestRepository
    ): Response {
        $user = $this->getUserByBearerToken($request);

        if (is_null($user)) {
            return $this->json([
                'error'   => true,
                'message' => 'Пользователь не авторизован',
            ]);
        }

        $supportRequest = $supportRequestRepository->findById($id);

        if (is_null($supportRequest)) {
            return $this->json([
                'error'   => true,
                'message' => sprintf('Не найдена заявка с id %s.', $id),
            ]);
        }

        if ($supportRequest->getCreatedBy()->getId() !== $user->getId()) {
            return $this->json([
                'error'   => true,
                'message' => 'Редактировать заявку может только создатель',
            ]);
        }

        $data = json_decode($request->getContent(), true);

        $requestDto = SupportRequestDTO::createFromEntity($supportRequest);

        $form = $this->createForm(SupportRequestType::class, $requestDto, [
            'csrf_protection' => false,
        ]);

        $form->submit($data);

        $supportRequest->updateFromDTO($requestDto);
        $this->entityManager->flush();

        return $this->json([
            'success' => true,
        ]);
    }
    /**
     * @Route("/add", name="api.request.add")
     */
    public function addSupportRequestAction(
        Request $request,
        SupportRequestApiDataManager $supportRequestApiDataManager
    ): Response {
        $user = $this->getUserByBearerToken($request);

        if (is_null($user)) {
            return $this->json([
                'error'   => true,
                'message' => 'Пользователь не авторизован',
            ]);
        }
        $data = json_decode($request->getContent(), true);

        $requestDto = new SupportRequestDTO($user);

        $form = $this->createForm(SupportRequestType::class, $requestDto, [
            'csrf_protection' => false,
        ]);

        $form->submit($data);

        if ($form->isSubmitted()) {
            if ($form->isValid()) {
                $supportRequest = RequestEntity::createFromDTO($requestDto);
                $this->entityManager->persist($supportRequest);
                $this->entityManager->flush();
                $this->entityManager->refresh($supportRequest);

                return $this->json([
                    'success' => true,
                    'data'    => [
                        'id' => $supportRequest->getId(),
                    ],
                ]);
            } else {
                return $this->json([
                    'error'   => true,
                    'message' => (string)$form->getErrors(true, false),
                ]);
            }
        }

        return $this->json([
            'error'   => true,
            'message' => 'Пустой запрос',
        ]);
    }

    /**
     * @Route("/answer/{id}", name="api.request.answer")
     */
    public function answerAction(
        Request $request,
        int $id,
        SupportRequestRepository $supportRequestRepository
    ): Response {
        $user = $this->getUserByBearerToken($request);

        if (is_null($user)) {
            return $this->json([
                'error'   => true,
                'message' => 'Пользователь не авторизован',
            ]);
        }

        $supportRequest = $supportRequestRepository->findById($id);

        if (is_null($supportRequest)) {
            return $this->json([
                'error'   => true,
                'message' => sprintf('Не найдена заявка с id %s.', $id),
            ]);
        }

        if (!is_null($supportRequest->getAnswer())) {
            return $this->json([
                'error'   => true,
                'message' => sprintf('Ответ для заявки с id %s уже был дан.', $id),
            ]);
        }

        $data = json_decode($request->getContent(), true);
        $answerDto = new SupportRequestAnswerDTO($supportRequest, $user);

        $form = $this->createForm(SupportRequestAnswerType::class, $answerDto, [
            'csrf_protection' => false,
        ]);

        $form->handleRequest($data);

        if ($form->isSubmitted()) {
            if ($form->isValid()) {
                $answer = SupportRequestAnswer::createFromDto($answerDto);
                $supportRequest->setStatus($answerDto->getStatus());
                $this->entityManager->persist($answer);
                $this->entityManager->flush();

                return $this->json([
                    'success' => true,
                ]);
            } else {
                return $this->json([
                    'error'   => true,
                    'message' => (string)$form->getErrors(true, false),
                ]);
            }
        }

        return $this->json([
            'error'   => true,
            'message' => 'Пустой запрос',
        ]);
    }

    /**
     * @Route("/get-answer/{id}", name="request.get_answer")
     */
    public function getAnswerAction(
        Request $request,
        int $id,
        SupportRequestRepository $supportRequestRepository
    ): Response {
        $supportRequest = $supportRequestRepository->findById($id);

        if (is_null($supportRequest)) {
            return $this->json([
                'error'   => true,
                'message' => sprintf('Не найдена заявка с id %s.', $id),
            ]);
        }

        return $this->json([
            'success' => true,
            'data'    => $supportRequest->getAnswer() ? $supportRequest->getAnswer()->getData() : null
        ]);
    }

    private function getUserByBearerToken(Request $request): ?User
    {
        if ($request->headers->has('Authorization')
            && 0 === strpos($request->headers->get('Authorization'), 'Bearer ')) {
            $token = substr($request->headers->get('Authorization'), 7);

            return $this->userRepository->getUserByApiKey($token);
        }

        return null;
    }
}

templates/support-request/add.html.twig
{% extends 'base.html.twig' %}
{% form_theme form 'bootstrap_5_layout.html.twig' %}

{% block title %}Новый запрос{% endblock %}

{% block body %}
    <h1>Добавить новый запрос</h1>
    <div>
        {{ form(form) }}
    </div>
{% endblock %}

templates/support-request/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Список запросов{% endblock %}

{% block body %}
    <h1>Список запросов:</h1>
    <div>
        <table class="table table-hover">
            <thead>
            <tr>
                <th class="text-center" style="width: 80px">Номер</th>
                <th>Заголовок</th>
                <th class="text-center" style="width: 100px">Статус</th>
                <th class="text-center" style="width: 180px">Дата создания</th>
                <th style="width: 60px"></th>
            </tr>
            </thead>
            <tbody>
            {% for request in requestList %}
                <tr>
                    <td class="text-center">{{ request.id }}</td>
                    <td>{{ request.title }}</td>
                    <td class="text-center">
                        {% set badgeClass = 'bg-primary' %}
                        {% if request.status == 1 %}
                            {% set badgeClass = 'bg-success' %}
                        {% elseif request.status == 2 %}
                            {% set badgeClass = 'bg-danger' %}
                        {% endif %}

                        <div class="badge {{ badgeClass }}">
                            {{ constant('App\\Entity\\SupportRequest::STATUS_TITLE_LIST')[request.status] }}
                        </div>
                    </td>
                    <td class="text-center">{{ request.createAt.format('Y.m.d H:i:s') }}</td>
                    <td class="text-center">
                        <a class="btn btn-primary btn-sm" href="{{ path('request.show', {'id': request.id }) }}">
                            Посмотреть
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
{% endblock %}

templates/support-request/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ request.title }}{% endblock %}

{% block body %}
    <a class="btn btn-outline-primary btn-sm mb-2 ps-5 pe-5" href="{{ path('request.list') }}">К списку</a>
    <hr/>
    <div class="text-end">
        {% if app.user %}
            {% if not request.answered %}
                <a href="{{ path('request.edit', {'id': request.id}) }}"
                   class="btn btn-primary btn-sm">Редактировать</a>
            {% endif %}
            {% if request.createdBy.id == app.user.id %}
            {% endif %}
        {% endif %}
    </div>
    <div>
        <table class="table">
            <thead>
            <tbody>
            <tr>
                <td>Заголовок</td>
                <td>{{ request.title }}</td>
            </tr>
            <tr>
                <td>Сообщение</td>
                <td>{{ request.message }}</td>
            </tr>
            <tr>
                <td>Статус</td>
                <td>
                    {% set badgeClass = 'bg-primary' %}
                    {% if request.status == 1 %}
                        {% set badgeClass = 'bg-success' %}
                    {% elseif request.status == 2 %}
                        {% set badgeClass = 'bg-danger' %}
                    {% endif %}

                    <div class="badge {{ badgeClass }}">
                        {{ constant('App\\Entity\\SupportRequest::STATUS_TITLE_LIST')[request.status] }}
                    </div>
                </td>
            </tr>
            <tr>
                <td>Дата создания</td>
                <td>{{ request.createAt.format('Y.m.d H:i:s') }}</td>
            </tr>
            <tr>
                <td>Кем создано</td>
                <td>{{ request.createdBy.fullName }}</td>
            </tr>
            </tbody>
        </table>
    </div>
    {% if app.user and not request.answered %}
        <div class="container bg-light p-3">
            <h2>Ответить на заявку</h2>
            <div>
                {{ form(answeredForm) }}
            </div>
        </div>
    {% endif %}
    {% if request.answered %}
        <div class="container bg-light p-3">
            <h2>Ответ на заявку</h2>
            <table class="table">
                <tr>
                    <td>Кем решено</td>
                    <td>{{ request.answer.answeredBy.fullName }}</td>
                </tr>
                <tr>
                    <td>Ответ</td>
                    <td>{{ request.answer.answer }}</td>
                </tr>
            </table>
        </div>
    {% endif %}
{% endblock %}